import type { INodeProperties } from 'n8n-workflow';

export const sharedOptions: INodeProperties = {
	displayName: 'Additional Options',
	name: 'additionalOptions',
	type: 'collection',
	placeholder: 'Add Option',
	default: {},
	displayOptions: {
		show: {
			operation: ['convertHtml', 'convertUrl', 'convertTemplate'],
		},
	},
	options: [
		// ── Page Layout (most used) ──
		{
			displayName: 'Format',
			name: 'format',
			type: 'options',
			default: 'Letter',
			description: 'Paper size for the PDF. Takes priority over custom Width/Height if both are set. <a href="https://pdfbolt.com/docs/parameters#format" target="_blank">Learn&nbsp;more</a>',
			options: [
				{ name: 'Letter', value: 'Letter' },
				{ name: 'Legal', value: 'Legal' },
				{ name: 'Tabloid', value: 'Tabloid' },
				{ name: 'Ledger', value: 'Ledger' },
				{ name: 'A0', value: 'A0' },
				{ name: 'A1', value: 'A1' },
				{ name: 'A2', value: 'A2' },
				{ name: 'A3', value: 'A3' },
				{ name: 'A4', value: 'A4' },
				{ name: 'A5', value: 'A5' },
				{ name: 'A6', value: 'A6' },
			],
		},
		{
			displayName: 'Width',
			name: 'width',
			type: 'string',
			default: '',
			placeholder: 'e.g. 210mm, 8.5in, 800px',
			description: 'Custom page width. Supports px, in, cm, mm (px if omitted). Format takes priority if both are set. <a href="https://pdfbolt.com/docs/parameters#width" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Height',
			name: 'height',
			type: 'string',
			default: '',
			placeholder: 'e.g. 297mm, 11in, 1200px',
			description: 'Custom page height. Supports px, in, cm, mm (px if omitted). Format takes priority if both are set. <a href="https://pdfbolt.com/docs/parameters#height" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Print Background',
			name: 'printBackground',
			type: 'boolean',
			default: false,
			description: 'Whether to include background colors and images in the PDF. <a href="https://pdfbolt.com/docs/parameters#printbackground" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Landscape',
			name: 'landscape',
			type: 'boolean',
			default: false,
			description: 'Whether to generate the PDF in landscape (horizontal) orientation. <a href="https://pdfbolt.com/docs/parameters#landscape" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Margin Top',
			name: 'marginTop',
			type: 'string',
			default: '',
			placeholder: 'e.g. 20px, 1cm',
			description: 'Top page margin. Supports px, in, cm, mm (px if omitted). <a href="https://pdfbolt.com/docs/parameters#margin" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Margin Right',
			name: 'marginRight',
			type: 'string',
			default: '',
			placeholder: 'e.g. 20px, 1cm',
			description: 'Right page margin. Supports px, in, cm, mm (px if omitted). <a href="https://pdfbolt.com/docs/parameters#margin" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Margin Bottom',
			name: 'marginBottom',
			type: 'string',
			default: '',
			placeholder: 'e.g. 20px, 1cm',
			description: 'Bottom page margin. Supports px, in, cm, mm (px if omitted). <a href="https://pdfbolt.com/docs/parameters#margin" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Margin Left',
			name: 'marginLeft',
			type: 'string',
			default: '',
			placeholder: 'e.g. 20px, 1cm',
			description: 'Left page margin. Supports px, in, cm, mm (px if omitted). <a href="https://pdfbolt.com/docs/parameters#margin" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Scale',
			name: 'scale',
			type: 'number',
			typeOptions: {
				minValue: 0.1,
				maxValue: 2,
				numberStepSize: 0.1,
			},
			default: 1,
			description: 'Zoom level for the page content (0.1 to 2.0). <a href="https://pdfbolt.com/docs/parameters#scale" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Page Ranges',
			name: 'pageRanges',
			type: 'string',
			default: '',
			placeholder: 'e.g. 1-3, 5, 8-11',
			description: 'Which pages to include in the PDF (e.g. 1-3, 5). Leave empty for all pages. <a href="https://pdfbolt.com/docs/parameters#pageranges" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Emulate Media Type',
			name: 'emulateMediaType',
			type: 'options',
			default: 'print',
			options: [
				{ name: 'Print', value: 'print' },
				{ name: 'Screen', value: 'screen' },
			],
			description: 'Which CSS styles to use: "print" renders the print version of the page (default), "screen" renders it as it looks in a browser. <a href="https://pdfbolt.com/docs/parameters#emulatemediatype" target="_blank">Learn&nbsp;more</a>',
		},

		// ── Output ──
		{
			displayName: 'Filename',
			name: 'filename',
			type: 'string',
			default: '',
			placeholder: 'e.g. invoice_001',
			description: 'Filename for the PDF (max 255 chars, letters / numbers / dots / underscores / hyphens). The .pdf extension is added automatically. <a href="https://pdfbolt.com/docs/parameters#filename" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Compression',
			name: 'compression',
			type: 'options',
			default: '',
			options: [
				{ name: 'None', value: '' },
				{ name: 'Lossless (Downscale Only, No Quality Loss)', value: 'lossless' },
				{ name: 'Low (Highest Quality, Largest File Size)', value: 'low' },
				{ name: 'Medium (Balanced Quality, Moderate File Size)', value: 'medium' },
				{ name: 'High (Lowest Quality, Smallest File Size)', value: 'high' },
			],
			description: 'Reduce PDF file size. Most effective on image-heavy documents. <a href="https://pdfbolt.com/docs/parameters#compression" target="_blank">Learn&nbsp;more</a>',
		},

		// ── Header & Footer ──
		{
			displayName: 'Header Template',
			name: 'headerTemplate',
			type: 'string',
			typeOptions: { rows: 4 },
			default: '',
			placeholder: '<div style="font-size:10px; width:100%; text-align:center;"><span class="pageNumber"></span> / <span class="totalPages"></span></div>',
			description: 'HTML template for page header. Add top margin to prevent overlap. Use classes: pageNumber, totalPages, date, title, url for dynamic content. Only inline CSS, inline SVG, and base64 images work – no external images, fonts, or scripts. <a href="https://pdfbolt.com/docs/parameters#headertemplate" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Footer Template',
			name: 'footerTemplate',
			type: 'string',
			typeOptions: { rows: 4 },
			default: '',
			placeholder: '<div style="font-size:10px; width:100%; text-align:center;"><span class="pageNumber"></span> / <span class="totalPages"></span></div>',
			description: 'HTML template for page footer. Add bottom margin to prevent overlap. Use classes: pageNumber, totalPages, date, title, url for dynamic content. Only inline CSS, inline SVG, and base64 images work – no external images, fonts, or scripts. <a href="https://pdfbolt.com/docs/parameters#footertemplate" target="_blank">Learn&nbsp;more</a>',
		},

		// ── Rendering ──
		{
			displayName: 'Timeout (ms)',
			name: 'timeout',
			type: 'number',
			typeOptions: { minValue: 1, maxValue: 60000 },
			default: 30000,
			description: 'Maximum wait time for the page to load, in milliseconds (e.g. 30000 = 30 seconds). <a href="https://pdfbolt.com/docs/parameters#timeout" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Wait Until',
			name: 'waitUntil',
			type: 'options',
			default: 'load',
			options: [
				{ name: 'Load (All Resources)', value: 'load' },
				{ name: 'DOM Content Loaded (HTML Parsed)', value: 'domcontentloaded' },
				{ name: 'Network Idle (No Requests for 500ms)', value: 'networkidle' },
				{ name: 'Commit (First Response Received)', value: 'commit' },
			],
			description: 'When to consider the page ready for PDF generation. Use "networkidle" for pages that load data dynamically. <a href="https://pdfbolt.com/docs/parameters#waituntil" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Wait For Function',
			name: 'waitForFunction',
			type: 'string',
			default: '',
			placeholder: "() => document.readyState === 'complete'",
			description: 'JavaScript function that must return true before the PDF is generated. <a href="https://pdfbolt.com/docs/parameters#waitforfunction" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Wait For Selector',
			name: 'waitForSelector',
			type: 'fixedCollection',
			default: {},
			typeOptions: { multipleValues: false },
			placeholder: 'Add Selector',
			options: [
				{
					name: 'values',
					displayName: 'Selector',
					values: [
						{
							displayName: 'CSS Selector',
							name: 'selector',
							type: 'string',
							default: '',
							placeholder: 'e.g. #content-loaded',
							description: 'CSS selector of the element to wait for. Ensure the selector exists on the page.',
						},
						{
							displayName: 'State',
							name: 'state',
							type: 'options',
							default: 'visible',
							options: [
								{ name: 'Visible (Element Is Displayed)', value: 'visible' },
								{ name: 'Hidden (Element Is Not Displayed)', value: 'hidden' },
								{ name: 'Attached (Element Exists, Even If Hidden)', value: 'attached' },
								{ name: 'Detached (Element Does Not Exist)', value: 'detached' },
							],
							description: 'Expected state of the element.',
						},
					],
				},
			],
			description: 'Wait for a CSS selector to reach a specific state before generating the PDF. <a href="https://pdfbolt.com/docs/parameters#waitforselector" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'JavaScript Enabled',
			name: 'javaScriptEnabled',
			type: 'boolean',
			default: true,
			description: 'Whether to run JavaScript on the page. Disable to speed up rendering, but dynamic content may not appear. <a href="https://pdfbolt.com/docs/parameters#javascriptenabled" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Tagged (Accessible PDF)',
			name: 'tagged',
			type: 'boolean',
			default: false,
			description: 'Whether to generate an accessible PDF with structural tags for screen readers. <a href="https://pdfbolt.com/docs/parameters#tagged" target="_blank">Learn&nbsp;more</a>',
		},

		// ── Viewport & Device ──
		{
			displayName: 'Viewport Size',
			name: 'viewportSize',
			type: 'fixedCollection',
			default: {},
			typeOptions: { multipleValues: false },
			placeholder: 'Add Viewport Size',
			options: [
				{
					name: 'values',
					displayName: 'Viewport',
					values: [
						{
							displayName: 'Width',
							name: 'width',
							type: 'number',
							default: 1280,
							description: 'Width in pixels. No units, just a number.',
						},
						{
							displayName: 'Height',
							name: 'height',
							type: 'number',
							default: 800,
							description: 'Height in pixels. No units, just a number.',
						},
					],
				},
			],
			description: 'Browser viewport size in pixels. Affects pages with responsive CSS (@media queries). <a href="https://pdfbolt.com/docs/parameters#viewportsize" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Is Mobile',
			name: 'isMobile',
			type: 'boolean',
			default: false,
			description: 'Enables mobile device emulation by respecting the meta viewport tag and enabling touch events. <a href="https://pdfbolt.com/docs/parameters#ismobile" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Device Scale Factor',
			name: 'deviceScaleFactor',
			type: 'number',
			typeOptions: { minValue: 1, maxValue: 4 },
			default: 1,
			description: 'Pixel density (1-4). Higher values produce sharper text and images but increase file size and slightly prolong processing time. <a href="https://pdfbolt.com/docs/parameters#devicescalefactor" target="_blank">Learn&nbsp;more</a>',
		},

		// ── HTTP ──
		{
			displayName: 'Cookies (JSON)',
			name: 'cookies',
			type: 'json',
			default: '',
			placeholder: '[{"name":"session","value":"abc123","url":"https://example.com"}]',
			description: 'JSON array of cookies (max 10). Each cookie needs: name, value, and either url OR both domain and path. Optional: expires (UNIX timestamp), httpOnly, secure. <a href="https://pdfbolt.com/docs/parameters#cookies" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Extra HTTP Headers',
			name: 'extraHTTPHeaders',
			type: 'fixedCollection',
			typeOptions: { multipleValues: true },
			default: {},
			placeholder: 'Add Header',
			options: [
				{
					name: 'values',
					displayName: 'Header',
					values: [
						{
							displayName: 'Key',
							name: 'key',
							type: 'string',
							default: '',
							placeholder: 'e.g. X-Custom-Header',
						},
						{
							displayName: 'Value',
							name: 'value',
							type: 'string',
							default: '',
							placeholder: 'e.g. my-value',
						},
					],
				},
			],
			description: 'Custom HTTP headers (max 10) sent with the request. <a href="https://pdfbolt.com/docs/parameters#extrahttpheaders" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Apply Extra Headers to All Resources',
			name: 'applyExtraHTTPHeadersToAllResources',
			type: 'boolean',
			default: true,
			description: 'Whether Extra HTTP Headers are sent with all requests (images, CSS, JS) or only the main page. Disable if external resources (CDNs) reject your custom headers. <a href="https://pdfbolt.com/docs/parameters#applyextrahttpheaderstoallresources" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'HTTP Credentials',
			name: 'httpCredentials',
			type: 'fixedCollection',
			default: {},
			typeOptions: { multipleValues: false },
			placeholder: 'Add Credentials',
			options: [
				{
					name: 'values',
					displayName: 'Credentials',
					values: [
						{
							displayName: 'Username',
							name: 'username',
							type: 'string',
							default: '',
						},
						{
							displayName: 'Password',
							name: 'password',
							type: 'string',
							typeOptions: { password: true },
							default: '',
						},
					],
				},
			],
			description: 'HTTP Basic Authentication for password-protected pages. <a href="https://pdfbolt.com/docs/parameters#httpcredentials" target="_blank">Learn&nbsp;more</a>',
		},

		// ── Less common ──
		{
			displayName: 'Prefer CSS Page Size',
			name: 'preferCssPageSize',
			type: 'boolean',
			default: false,
			description: 'Whether to use the CSS @page size defined in the page content instead of the Format/Width/Height settings. <a href="https://pdfbolt.com/docs/parameters#prefercsspagesize" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Content Disposition',
			name: 'contentDisposition',
			type: 'options',
			default: 'inline',
			options: [
				{ name: 'Inline (Display in Browser)', value: 'inline' },
				{ name: 'Attachment (Download as File)', value: 'attachment' },
			],
			description: 'Controls how the PDF is delivered: displayed in browser or downloaded as a file. <a href="https://pdfbolt.com/docs/parameters#contentdisposition" target="_blank">Learn&nbsp;more</a>',
		},

		// ── Print Production ──
		{
			displayName: 'PDF Standard',
			name: 'pdfStandard',
			type: 'options',
			default: '',
			options: [
				{ name: 'None', value: '' },
				{ name: 'PDF/X-4 (Recommended)', value: 'pdf-x-4' },
				{ name: 'PDF/X-1a (Strict)', value: 'pdf-x-1a' },
			],
			description: 'PDF/X compliance for professional printing. PDF/X-4 – modern standard supporting transparency. PDF/X-1a – strict, no transparency. Both auto-convert to CMYK. <a href="https://pdfbolt.com/docs/parameters#pdfstandard" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Color Space',
			name: 'colorSpace',
			type: 'options',
			default: 'rgb',
			options: [
				{ name: 'RGB (Digital / Screens)', value: 'rgb' },
				{ name: 'CMYK (Professional Printing)', value: 'cmyk' },
			],
			description: 'RGB for screens (default). CMYK for professional printing. CMYK is required when using PDF Standard. <a href="https://pdfbolt.com/docs/parameters#colorspace" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'ICC Profile',
			name: 'iccProfile',
			type: 'options',
			default: 'fogra39',
			options: [
				{ name: 'FOGRA39 (Europe, Coated)', value: 'fogra39' },
				{ name: 'FOGRA51 (Europe, Modern)', value: 'fogra51' },
				{ name: 'SWOP (North America, Web Offset)', value: 'swop' },
				{ name: 'GRACoL (North America, Commercial)', value: 'gracol' },
			],
			description: 'Color profile for RGB-to-CMYK conversion. Europe: FOGRA51 (modern) or FOGRA39 (most common). North America: GRACoL (commercial) or SWOP (web offset). <a href="https://pdfbolt.com/docs/parameters#iccprofile" target="_blank">Learn&nbsp;more</a>',
		},
		{
			displayName: 'Preserve Black',
			name: 'preserveBlack',
			type: 'boolean',
			default: true,
			description: 'Whether pure black (#000) maps to 100% K ink only (sharp text and lines) or gets converted to rich black through ICC profile (deeper black for large areas). <a href="https://pdfbolt.com/docs/parameters#preserveblack" target="_blank">Learn&nbsp;more</a>',
		},
	],
};
